### ISSUE TITLE
No distinction between monadic and dyadic functions

### ISSUE THREAD

**Issue by crmsnbleyd** [shnarazk/tree-sitter-uiua#24]
It would be useful if there were different characteristics between monadic and dyadic functions, for example divide and length, so that they can be highlighted differently, like in the pad. Does that make sense?

**Comment by shnarazk** [comment]
I categorized modifiers but did not categorize functions due to my laziness. 
Do you request this feature?
We need to check all functions and find the nomadic function `now` and the triadic function `insert`. No other arities? I will probably not assign specific colors to each in queries/highlights.js. The categorization used in it is not so fine-grained compared with the pad.
If you write highlight.js for your editor for your color theme, it definitely makes sense.
